import { createHash } from 'node:crypto';
import { z } from 'zod';
import { canonicalRuleHost, createReferralAssessor, type ReferralPolicy } from '../../analytics/src/referral-policy.js';

export const revisionSchema = z.string().regex(/^[0-9a-f]{40}$/);
export const digestSchema = z.string().regex(/^[0-9a-f]{64}$/);
export const policyVersionSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}\.\d+$/);
export const sourceManifestSchema = z.object({
  provider: z.literal('matomo'),
  repository: z.literal('https://github.com/matomo-org/referrer-spam-list'),
  revision: revisionSchema,
  capturedAt: z.string().datetime(),
  license: z.literal('CC0-1.0'),
  files: z.object({ 'spammers.txt': digestSchema, 'README.md': digestSchema, 'composer.json': digestSchema }),
  entryCount: z.number().int().positive(),
}).strict();
export const policySpecSchema = z.object({
  version: policyVersionSchema,
  evaluator: z.literal('host-suffix-v1'),
  sourceRevision: revisionSchema,
  localRules: z.array(z.object({
    id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,63}$/),
    host: z.string(), scope: z.enum(['host', 'subtree']), action: z.enum(['include', 'exclude']),
    reason: z.string().trim().min(1), evidence: z.string().trim().min(1),
  }).strict()),
  publicHosts: z.array(z.string()),
}).strict();
export type PolicySpec = z.infer<typeof policySpecSchema>;
export type SourceManifest = z.infer<typeof sourceManifestSchema>;
export const referralEvidenceSchema = z.array(z.object({
  success: z.literal(true),
  results: z.array(z.object({ referrer_host: z.string().nullable() }).passthrough()),
  meta: z.object({ rows_written: z.literal(0) }).passthrough(),
})).min(1);

export function sha256(value: string | Uint8Array): string {
  return createHash('sha256').update(value).digest('hex');
}

export function parseSpammerHosts(raw: string): string[] {
  const hosts = new Set<string>();
  for (const line of raw.split(/\r?\n/)) {
    if (line.length === 0) continue; // Matomo explicitly permits empty lines.
    const host = canonicalRuleHost(line);
    if (hosts.has(host)) throw new Error(`Duplicate canonical source hostname: ${host}`);
    hosts.add(host);
  }
  if (hosts.size < 10 || hosts.size > 10000) throw new Error('Unexpected upstream list size; review before importing');
  return [...hosts].sort();
}

export function compileReferralPolicy(spec: PolicySpec, source: SourceManifest, raw: string): ReferralPolicy {
  if (source.revision !== spec.sourceRevision || sha256(raw) !== source.files['spammers.txt']) {
    throw new Error('Policy source revision/hash mismatch');
  }
  const upstreamHosts = parseSpammerHosts(raw);
  if (upstreamHosts.length !== source.entryCount) throw new Error('Source count mismatch');
  const ids = new Set<string>();
  const localHosts = new Set<string>();
  for (const rule of spec.localRules) {
    if (canonicalRuleHost(rule.host) !== rule.host) throw new Error('Local rule hostname must be canonical');
    if (ids.has(rule.id) || localHosts.has(`${rule.host}/${rule.scope}`)) throw new Error('Duplicate or conflicting local rule');
    ids.add(rule.id);
    localHosts.add(`${rule.host}/${rule.scope}`);
  }
  const publicHosts = [...new Set(spec.publicHosts)].sort();
  if (publicHosts.length !== spec.publicHosts.length || publicHosts.some(host => canonicalRuleHost(host) !== host || host.startsWith('www.'))) {
    throw new Error('Display hosts must be unique canonical hosts without www aliases');
  }
  const definition = {
    version: spec.version, evaluator: spec.evaluator,
    source: { provider: source.provider, revision: source.revision, sha256: source.files['spammers.txt'], capturedAt: source.capturedAt, entryCount: source.entryCount },
    upstreamHosts,
    localRules: [...spec.localRules].sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0),
    publicHosts,
  };
  const policy = { ...definition, sha256: sha256(JSON.stringify(definition)) };
  const assess = createReferralAssessor(policy);
  for (const host of publicHosts) {
    if (assess(host).action === 'exclude') throw new Error(`Display/exclusion conflict for ${host}; resolve explicitly`);
  }
  return policy;
}

export function renderPolicyModule(policy: ReferralPolicy): string {
  return `// Generated by scripts/referral-policy.ts build. Archive: policies/${policy.version}.json\n`
    + `import type { ReferralPolicy } from './referral-policy.js';\n\n`
    + `export const ACTIVE_REFERRAL_POLICY: ReferralPolicy = ${JSON.stringify(policy, null, 2)};\n`;
}

export function verifyPolicyCommitment(policy: ReferralPolicy, commitment: string | undefined, allowNew = false): void {
  if (commitment === undefined) {
    if (!allowNew) throw new Error('Missing policy commitment: build and review this version first');
  } else if (commitment !== policy.sha256) {
    throw new Error('Existing policy changed: create a new version');
  }
}

/** Store the received JSON itself so future policy/data changes cannot revise it. */
export function reportEvidence(body: string, requestUrl: string, capturedAt: string, policy: ReferralPolicy) {
  const report = z.object({
    period: z.object({ start: z.string(), end: z.string(), updatedAt: z.string() }).passthrough(),
    filters: z.object({ range: z.string(), traffic: z.string() }).passthrough(),
    totals: z.object({ views: z.number().int().nonnegative() }).passthrough(),
    byReferrer: z.array(z.object({ referrerHost: z.string(), views: z.number().int().nonnegative() })),
    otherReferrerViews: z.number().int().nonnegative(),
    referralPolicy: z.object({
      version: policyVersionSchema, sha256: digestSchema, evaluator: z.literal('host-suffix-v1'),
      source: z.object({ provider: z.literal('matomo'), revision: revisionSchema, sha256: digestSchema }),
      excludedViews: z.number().int().nonnegative(),
    }),
  }).passthrough().parse(JSON.parse(body));
  const provenance = report.referralPolicy;
  if (provenance.version !== policy.version || provenance.sha256 !== policy.sha256
    || provenance.evaluator !== policy.evaluator || provenance.source.revision !== policy.source.revision
    || provenance.source.sha256 !== policy.source.sha256) throw new Error('Report does not use the requested archived policy');
  if (report.byReferrer.some(row => !policy.publicHosts.includes(row.referrerHost))) throw new Error('Report exposes an unapproved referrer name');
  return {
    schemaVersion: 1, capturedAt, requestUrl, responseSha256: sha256(body),
    policyVersion: policy.version, policySha256: policy.sha256,
    // A report capture time is not a deployment activation time.
    period: report.period, filters: report.filters, responseBody: body,
  };
}

export function policyDifference(previous: ReferralPolicy, next: ReferralPolicy) {
  const before = new Set(previous.upstreamHosts);
  const after = new Set(next.upstreamHosts);
  return {
    previous: previous.version, next: next.version,
    added: [...after].filter(host => !before.has(host)), removed: [...before].filter(host => !after.has(host)),
    localRulesChanged: JSON.stringify(previous.localRules) !== JSON.stringify(next.localRules),
    displayChanged: JSON.stringify(previous.publicHosts) !== JSON.stringify(next.publicHosts),
  };
}
