import { html, raw } from 'nisli-static';
import type { PostMeta, PromptsData } from '../lib/frontmatter.js';
import { formatDateLong } from '../lib/dates.js';

export function postTemplate(meta: PostMeta, htmlContent: string, prompts?: PromptsData | null) {
  const dateStr = formatDateLong(meta.date);

  return html`<article>
  <header class="post-header">
    <time datetime="${meta.date}">${dateStr}</time>${prompts ? html`<span class="post-header-sep"> · </span><a href="/${meta.slug}/prompts" class="post-header-prompts"><img src="/icons/transparency.svg" width="14" height="14" alt="" class="post-header-prompts-icon">Prompted by human, generated by AI<span class="post-header-prompts-count"> — ${prompts.count} prompt${prompts.count === 1 ? '' : 's'}</span></a>` : ''}
    ${meta.tags.length > 0
      ? html`<div class="tags">${meta.tags.map(t => html`<span class="tag">${t}</span>`)}</div>`
      : ''}
  </header>
  <div class="post-content">
    ${raw(htmlContent)}
  </div>
  ${prompts ? html`
  <section class="prompts-teaser">
    <div class="prompts-teaser-header">
      <img src="/icons/transparency.svg" width="16" height="16" alt="">
      <strong>Prompted by human, generated by AI</strong>
      <span class="prompts-teaser-count">${prompts.count} prompt${prompts.count === 1 ? '' : 's'}</span>
    </div>
    <p class="prompts-teaser-preview">"${prompts.preview}"</p>
    <a href="/${meta.slug}/prompts" class="prompts-teaser-link">See behind the scenes →</a>
  </section>` : ''}
</article>`;
}
